# Generated by Django 5.2.8 on 2025-11-17 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('', 'Select Gender'), ('male', 'Male'), ('female', 'Female'), ('others', 'Others')], max_length=10)),
                ('blood', models.CharField(choices=[('', 'Select BloodGroup'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=5)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('health', models.TextField()),
                ('last', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
