# Generated by Django 5.2.8 on 2025-11-18 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='email',
        ),
        migrations.AddField(
            model_name='donor',
            name='alcoholic',
            field=models.CharField(choices=[('', 'Are you an alcoholic?'), ('yes', 'Yes'), ('no', 'No')], default='no', max_length=3),
        ),
        migrations.AddField(
            model_name='donor',
            name='smoker',
            field=models.CharField(choices=[('', 'Are you a smoker?'), ('yes', 'Yes'), ('no', 'No')], default='no', max_length=3),
        ),
    ]
