# Generated by Django 5.2.8 on 2025-11-18 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodapp', '0002_remove_donor_email_donor_alcoholic_donor_smoker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='alcoholic',
            field=models.CharField(choices=[('', 'Are you an alcoholic?'), ('yes', 'Yes'), ('no', 'No')], default='Are you an alcoholic?', max_length=3),
        ),
        migrations.AlterField(
            model_name='donor',
            name='smoker',
            field=models.CharField(choices=[('', 'Are you a smoker?'), ('yes', 'Yes'), ('no', 'No')], default='Are you a smoker?', max_length=3),
        ),
    ]
