# Generated by Django 5.2.8 on 2025-11-18 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodapp', '0003_alter_donor_alcoholic_alter_donor_smoker'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('', 'Gender'), ('male', 'Male'), ('female', 'Female'), ('others', 'Others')], max_length=6)),
                ('blood', models.CharField(choices=[('', 'Required Blood Group'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3)),
                ('units', models.IntegerField()),
                ('urgent', models.CharField(choices=[('', 'Urgency Level'), ('normal', 'Normal'), ('urgent', 'Urgent'), ('emergency', 'Emergency')], max_length=10)),
                ('date', models.DateField()),
                ('hos', models.CharField(max_length=100)),
                ('add', models.CharField(max_length=100)),
                ('requester', models.CharField(max_length=30)),
            ],
        ),
    ]
