# Generated by Django 5.2.8 on 2025-11-19 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodapp', '0004_recipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipient',
            name='status',
            field=models.CharField(default='Pending', max_length=10),
        ),
    ]
