# Generated by Django 5.2.8 on 2025-11-19 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodapp', '0006_alter_recipient_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipient',
            name='status',
            field=models.CharField(blank=True, default='Pending', max_length=10, null=True),
        ),
    ]
