# Generated by Django 5.2.8 on 2025-11-19 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodapp', '0007_alter_recipient_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='address',
        ),
        migrations.AddField(
            model_name='donor',
            name='units',
            field=models.IntegerField(default=1),
        ),
    ]
