# Generated by Django 5.2.8 on 2025-11-21 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodapp', '0011_bloodstock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodstock',
            name='units',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='donor',
            name='units',
            field=models.IntegerField(),
        ),
    ]
