# Generated by Django 5.2.8 on 2025-11-21 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodapp', '0012_alter_bloodstock_units_alter_donor_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodstock',
            name='units',
            field=models.IntegerField(default=0),
        ),
    ]
